### ISSUE TITLE
[Bug] Can't Pull Through Reach

### ISSUE THREAD

**Issue by alexmacartney** [fivetran/dbt_facebook_ads_source#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

`reach` is already being pulled through manually in stg_facebook_ads__basic_ad.sql so when I try to pass through `reach` using the below I get a duplicate field and the model can't run. I need to pass through the field for subsequent models using the dbt_facebook_ads repo. I believe the same would be true for `frequency`.

```
facebook_ads__basic_ad_passthrough_metrics: 
  - name: "reach"
```

### Relevant error log or model output

```shell
with base as (
    select * 
    from `analytics-dev-406710`.`alex_analytics_dev_package_fivetran_ads_source`.`stg_facebook_ads__basic_ad_tmp`
),
fields as (
    select
        
    
    
    ad_id
    
 as 
    
    ad_id
    
, 
    
    
    ad_name
    
 as 
    
    ad_name
    
, 
    
    
    adset_name
    
 as 
    
    adset_name
    
, 
    
    
    date
    
 as 
    
    date
    
, 
    
    
    account_id
    
 as 
    
    account_id
    
, 
    
    
    impressions
    
 as 
    
    impressions
    
, 
    
    
    inline_link_clicks
    
 as 
    
    inline_link_clicks
    
, 
    
    
    spend
    
 as 
    
    spend
    
, 
    
    
    reach
    
 as 
    
    reach
    
, 
    
    
    frequency
    
 as 
    
    frequency
    
, 
    
    
    reach
    
 as 
    
    reach
    
        
    
        
, cast('' as STRING) as source_relation
    from base
),
final as (
    select
        source_relation, 
        cast(ad_id as bigint) as ad_id,
        ad_name,
        adset_name as ad_set_name,
        date as date_day,
        cast(account_id as bigint) as account_id,
        impressions,
        coalesce(inline_link_clicks,0) as clicks,
        spend,
        reach,
        frequency
        
    
        
            
                , reach
            
        
    
    from fields
)
select * 
from final
```

### Expected behavior

I would expect `reach` to not be in the initial list of variables so that when the macro adds it there are no duplicate fields. This would then allow the model to run.

### dbt Project configurations

```
facebook_ads__basic_ad_passthrough_metrics: 
  - name: "reach"
```

### Package versions

```
packages:

  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]
  
  - package: Velir/ga4
    version: 5.1.0

  - package: fivetran/google_ads
    version: [">=0.10.0", "<0.11.0"]
  
  - package: fivetran/facebook_ads
    version: [">=0.7.0", "<0.8.0"]

  - package: fivetran/instagram_business
    version: [">=0.2.0", "<0.3.0"]

```

### What database are you using dbt with?

bigquery

### dbt Version

Core:
  - installed: 1.6.6 
  - latest:    1.7.13 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.6.7 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
